DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'psikotes_runtime') THEN
        CREATE ROLE psikotes_runtime NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
    END IF;
END
$$;

ALTER ROLE psikotes_runtime NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;

CREATE SCHEMA IF NOT EXISTS dass;

DO $$
BEGIN
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO psikotes_runtime', current_database());
END
$$;
GRANT USAGE ON SCHEMA public, dass TO psikotes_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public, dass TO psikotes_runtime;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public, dass TO psikotes_runtime;

ALTER DEFAULT PRIVILEGES IN SCHEMA public, dass
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO psikotes_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public, dass
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO psikotes_runtime;
