DROP POLICY IF EXISTS dass_results_write ON dass.results;
DROP POLICY IF EXISTS dass_results_read ON dass.results;
DROP POLICY IF EXISTS dass_responses_write ON dass.responses;
DROP POLICY IF EXISTS dass_responses_read ON dass.responses;
DROP POLICY IF EXISTS dass_assessments_write ON dass.assessments;
DROP POLICY IF EXISTS dass_assessments_read ON dass.assessments;
DROP POLICY IF EXISTS outbox_messages_service ON outbox_messages;
DROP POLICY IF EXISTS audit_logs_checkout_consent_privacy ON audit_logs;
DROP POLICY IF EXISTS audit_logs_write ON audit_logs;
DROP POLICY IF EXISTS audit_logs_read ON audit_logs;
DROP POLICY IF EXISTS entitlements_write ON entitlements;
DROP POLICY IF EXISTS entitlements_read ON entitlements;
DROP POLICY IF EXISTS orders_write ON orders;
DROP POLICY IF EXISTS orders_read ON orders;
DROP POLICY IF EXISTS payment_methods_write ON payment_methods;
DROP POLICY IF EXISTS payment_methods_read ON payment_methods;
DROP POLICY IF EXISTS consent_records_write ON consent_records;
DROP POLICY IF EXISTS consent_records_read ON consent_records;
DROP POLICY IF EXISTS referral_visits_write ON referral_visits;
DROP POLICY IF EXISTS referral_visits_read ON referral_visits;
DROP POLICY IF EXISTS participants_write ON participants;
DROP POLICY IF EXISTS participants_read ON participants;
DROP POLICY IF EXISTS admins_write ON admins;
DROP POLICY IF EXISTS admins_read ON admins;
DROP POLICY IF EXISTS branches_write ON branches;
DROP POLICY IF EXISTS branches_read ON branches;

ALTER TABLE dass.results NO FORCE ROW LEVEL SECURITY;
ALTER TABLE dass.results DISABLE ROW LEVEL SECURITY;
ALTER TABLE dass.responses NO FORCE ROW LEVEL SECURITY;
ALTER TABLE dass.responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE dass.assessments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE dass.assessments DISABLE ROW LEVEL SECURITY;
ALTER TABLE outbox_messages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE outbox_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE entitlements NO FORCE ROW LEVEL SECURITY;
ALTER TABLE entitlements DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders NO FORCE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_methods NO FORCE ROW LEVEL SECURITY;
ALTER TABLE payment_methods DISABLE ROW LEVEL SECURITY;
ALTER TABLE consent_records NO FORCE ROW LEVEL SECURITY;
ALTER TABLE consent_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE referral_visits NO FORCE ROW LEVEL SECURITY;
ALTER TABLE referral_visits DISABLE ROW LEVEL SECURITY;
ALTER TABLE participants NO FORCE ROW LEVEL SECURITY;
ALTER TABLE participants DISABLE ROW LEVEL SECURITY;
ALTER TABLE admins NO FORCE ROW LEVEL SECURITY;
ALTER TABLE admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE branches NO FORCE ROW LEVEL SECURITY;
ALTER TABLE branches DISABLE ROW LEVEL SECURITY;

DROP SCHEMA IF EXISTS app_private CASCADE;
